import {
  Employee,
  Holiday,
  LeaveBalance,
  LeaveRequest,
  SalaryConfig,
  SalaryRecord,
  TimeEntry,
  PayrollSettings,
} from '@/types';

const now = new Date();
const iso = (date: Date) => date.toISOString();

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    email: 'admin@hrms.dev',
    first_name: 'Alex',
    last_name: 'Admin',
    designation: 'HR Manager',
    department: 'HR',
    join_date: '2024-01-05',
    date_of_birth: '1990-03-15',
    phone_number: '555-111-2222',
    address: '123 Main St',
    gender: 'male',
    employee_id: 'HR-001',
    employment_type: 'full_time',
    emergency_contact_name: 'Jamie Admin',
    emergency_contact_relation: 'Partner',
    emergency_contact_phone: '555-333-4444',
    standard_shift_start: '09:00',
    standard_shift_end: '17:00',
    standard_hours_per_day: 8,
    is_admin: true,
    is_active: true,
    created_at: iso(new Date(now.getFullYear(), 0, 5)),
    updated_at: iso(new Date(now.getFullYear(), 10, 1)),
  },
  {
    id: 'emp-2',
    email: 'jordan@hrms.dev',
    first_name: 'Jordan',
    last_name: 'Employee',
    designation: 'Product Designer',
    department: 'Design',
    join_date: '2024-02-10',
    date_of_birth: '1994-08-22',
    phone_number: '555-222-3333',
    address: '456 Market St',
    gender: 'female',
    employee_id: 'DS-010',
    employment_type: 'full_time',
    emergency_contact_name: 'Taylor Employee',
    emergency_contact_relation: 'Sibling',
    emergency_contact_phone: '555-444-5555',
    standard_shift_start: '09:30',
    standard_shift_end: '17:30',
    standard_hours_per_day: 8,
    is_admin: false,
    is_active: true,
    created_at: iso(new Date(now.getFullYear(), 1, 10)),
    updated_at: iso(new Date(now.getFullYear(), 9, 15)),
  },
];

export const initialPasswords: Record<string, string> = {
  'admin@hrms.dev': 'password',
  'jordan@hrms.dev': 'password',
};

export const initialTimeEntries: TimeEntry[] = [
  {
    id: 'time-1',
    employee_id: 'emp-2',
    date: '2024-11-25',
    time_in: iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2, 9, 35)),
    time_out: iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2, 17, 45)),
    total_hours: 8.17,
    overtime_hours: 0.17,
    is_late: true,
    is_early_leave: false,
    notes: '',
    created_at: iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2, 9, 35)),
    updated_at: iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 2, 17, 45)),
  },
  {
    id: 'time-2',
    employee_id: 'emp-2',
    date: '2024-11-26',
    time_in: iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 9, 20)),
    time_out: iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 17, 20)),
    total_hours: 8,
    overtime_hours: 0,
    is_late: false,
    is_early_leave: false,
    notes: '',
    created_at: iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 9, 20)),
    updated_at: iso(new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1, 17, 20)),
  },
];

export const initialLeaveBalances: LeaveBalance[] = [
  {
    id: 'lb-1',
    employee_id: 'emp-2',
    leave_type: 'paid',
    total_days: 18,
    used_days: 6,
    remaining_days: 12,
    year: now.getFullYear(),
    created_at: iso(new Date(now.getFullYear(), 0, 1)),
    updated_at: iso(new Date(now.getFullYear(), 9, 15)),
  },
  {
    id: 'lb-2',
    employee_id: 'emp-2',
    leave_type: 'sick',
    total_days: 8,
    used_days: 2,
    remaining_days: 6,
    year: now.getFullYear(),
    created_at: iso(new Date(now.getFullYear(), 0, 1)),
    updated_at: iso(new Date(now.getFullYear(), 8, 1)),
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: 'lr-1',
    employee_id: 'emp-2',
    leave_type: 'paid',
    start_date: '2024-12-12',
    end_date: '2024-12-13',
    is_half_day: false,
    total_days: 2,
    reason: 'Family event',
    status: 'approved',
    approver_id: 'emp-1',
    approver_comment: 'Enjoy!',
    approved_at: iso(new Date(now.getFullYear(), 10, 1)),
    created_at: iso(new Date(now.getFullYear(), 9, 20)),
    updated_at: iso(new Date(now.getFullYear(), 10, 1)),
  },
  {
    id: 'lr-2',
    employee_id: 'emp-2',
    leave_type: 'sick',
    start_date: '2024-11-10',
    end_date: '2024-11-10',
    is_half_day: true,
    total_days: 0.5,
    reason: 'Doctor appointment',
    status: 'approved',
    approver_id: 'emp-1',
    approver_comment: '',
    approved_at: iso(new Date(now.getFullYear(), 10, 2)),
    created_at: iso(new Date(now.getFullYear(), 9, 25)),
    updated_at: iso(new Date(now.getFullYear(), 10, 2)),
  },
];

export const initialHolidays: Holiday[] = [
  {
    id: 'holiday-1',
    name: 'New Year',
    date: `${now.getFullYear()}-01-01`,
    is_recurring: true,
    description: 'Company holiday',
    created_at: iso(new Date(now.getFullYear() - 1, 11, 1)),
    updated_at: iso(new Date(now.getFullYear() - 1, 11, 1)),
  },
  {
    id: 'holiday-2',
    name: 'Founders Day',
    date: `${now.getFullYear()}-02-15`,
    is_recurring: false,
    description: 'Celebration of company founding',
    created_at: iso(new Date(now.getFullYear() - 1, 11, 1)),
    updated_at: iso(new Date(now.getFullYear() - 1, 11, 1)),
  },
];

export const initialSalaryConfigs: SalaryConfig[] = [
  {
    id: 'salcfg-1',
    employee_id: 'emp-2',
    salary_type: 'monthly',
    base_amount: 5000,
    overtime_multiplier: 1.5,
    currency: 'USD',
    effective_from: `${now.getFullYear()}-01-01`,
    effective_to: undefined,
    created_at: iso(new Date(now.getFullYear() - 1, 11, 1)),
    updated_at: iso(new Date(now.getFullYear(), 9, 10)),
  },
];

export const initialSalaryRecords: SalaryRecord[] = [
  {
    id: 'salrec-1',
    employee_id: 'emp-2',
    period_month: now.getMonth() + 1,
    period_year: now.getFullYear(),
    working_days: 22,
    days_present: 20,
    days_absent: 2,
    paid_leave_days: 1,
    unpaid_leave_days: 1,
    total_hours_worked: 160,
    overtime_hours: 6,
    late_arrivals: 2,
    early_leaves: 1,
    base_pay: 5000,
    overtime_pay: 300,
    allowances: 200,
    unpaid_leave_deduction: 150,
    other_deductions: 50,
    net_pay: 5300,
    is_provisional: false,
    notes: 'Includes project bonus',
    created_at: iso(new Date(now.getFullYear(), now.getMonth(), 1)),
    updated_at: iso(new Date(now.getFullYear(), now.getMonth(), 28)),
  },
];

export const initialPayrollSettings: PayrollSettings = {
  id: 'payroll-1',
  hourly_rate: 30,
  overtime_multiplier: 1.5,
  standard_working_days_per_month: 22,
  deduction_type: 'daily',
  daily_deduction_rate: 120,
  currency: 'USD',
  created_at: iso(new Date(now.getFullYear() - 1, 11, 1)),
  updated_at: iso(new Date(now.getFullYear(), 9, 1)),
};

